# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b7b0032250b2abb3f5c8cc8e6366041a"
name = "dityy-popup-manager by mekky"
application_url = "https://popup.muhammedmekky.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://popup.muhammedmekky.com/auth/callback" ]
